services:
  music-bot:
    build: .
    container_name: telegram-music-bot
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - .:/app
      - /var/www/tlgmusic:/var/www/tlgmusic:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always # Только один раз!
